// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD2ihtyslJIdIR3yR7CLA6SXWi5zhDrqI0',
    appId: '1:495468085476:web:5e808fd6f86e7c9a892cf1',
    messagingSenderId: '495468085476',
    projectId: 'quizmaker-f3c64',
    authDomain: 'quizmaker-f3c64.firebaseapp.com',
    storageBucket: 'quizmaker-f3c64.appspot.com',
    measurementId: 'G-MCL83Q4K3Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDJb7tYBe3PzAxVzkKZOeJBddB-Okf6g7U',
    appId: '1:495468085476:android:51ba3a9a32579e1c892cf1',
    messagingSenderId: '495468085476',
    projectId: 'quizmaker-f3c64',
    storageBucket: 'quizmaker-f3c64.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyABdjbopBWXKCMIk35bWC4hioR7BlEp2po',
    appId: '1:495468085476:ios:252924ee858d968b892cf1',
    messagingSenderId: '495468085476',
    projectId: 'quizmaker-f3c64',
    storageBucket: 'quizmaker-f3c64.appspot.com',
    iosClientId: '495468085476-8mg9uvvlpbq4n4i1s19u247a58hucn1j.apps.googleusercontent.com',
    iosBundleId: 'com.example.quizmaker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyABdjbopBWXKCMIk35bWC4hioR7BlEp2po',
    appId: '1:495468085476:ios:252924ee858d968b892cf1',
    messagingSenderId: '495468085476',
    projectId: 'quizmaker-f3c64',
    storageBucket: 'quizmaker-f3c64.appspot.com',
    iosClientId: '495468085476-8mg9uvvlpbq4n4i1s19u247a58hucn1j.apps.googleusercontent.com',
    iosBundleId: 'com.example.quizmaker',
  );
}
